In [1]:
import numpy as np

analiza biblioteki **języka Python** - <span style="font-size:16pt; color:red; font-family:Impact;">Numpy</span>

In [2]:
wektor = np.array([6,3,7,8,2,45,6,24,9])
wektor

array([ 6, 3, 7, 8, 2, 45, 6, 24, 9])

In [3]:
print(type(wektor))

<class 'numpy.ndarray'>


In [5]:
nb = [45,7,8,3,67,2,11,37,9]
nb = nb + wektor
nb

array([51, 10, 15, 11, 69, 47, 17, 61, 18])

In [6]:
print(type(nb))

<class 'numpy.ndarray'>


In [7]:
macierz = np.array([[1,2,3,4],[9,10,11,12],[34,56,78,13]])
macierz

array([[ 1, 2, 3, 4],
 [ 9, 10, 11, 12],
 [34, 56, 78, 13]])

In [8]:
macierz[1]

array([ 9, 10, 11, 12])

In [9]:
macierz[1][0]

9

In [10]:
macierz[1,0]

9

In [12]:
lista = [[2,6,9],[9,15,67],[18,4,2]]
lista

[[2, 6, 9], [9, 15, 67], [18, 4, 2]]

In [13]:
lista[0][2]

9

In [15]:
# lista[0,2]

In [17]:
nplista = np.array(lista)
nplista[0,2]

9

In [18]:
macierz[macierz<=5]

array([1, 2, 3, 4])

In [19]:
pc = (macierz>5)
macierz[pc]

array([ 9, 10, 11, 12, 34, 56, 78, 13])

In [20]:
lw = (macierz%2==0)
macierz[lw]

array([ 2, 4, 10, 12, 34, 56, 78])

In [21]:
cv = macierz[(macierz>2)&(macierz<=21)]
cv

array([ 3, 4, 9, 10, 11, 12, 13])

In [22]:
dane = np.array([1,3,8])
one = np.ones(3,dtype=int)
tw = np.array([2,2,3])

In [23]:
#dodawnie wektorów
dane + one

array([2, 4, 9])

In [24]:
dane - one

array([0, 2, 7])

In [25]:
dane*tw

array([ 2, 6, 24])

In [26]:
dane/tw

array([0.5 , 1.5 , 2.66666667])

In [27]:
print(dane*1.04)

[1.04 3.12 8.32]


In [28]:
m1 = np.array([[4,8,11],[67,101,3],[1,1,77]])
m2 = np.array([[488,9,3],[23,89,2],[2,4,11]])

In [29]:
wynik = (m1+m2)*m1
wynik

array([[ 1968, 136, 154],
 [ 6030, 19190, 15],
 [ 3, 5, 6776]])

In [31]:
print(f"wartość minimum: {wynik.min()}")
print(f"wartość maximum: {wynik.max()}")
print(f"wartość średnia: {wynik.mean()}")
print(f"wartość odchylenia standardowego: {wynik.std()}")

wartość minimum: 3
wartość maximum: 19190
wartość średnia: 3808.5555555555557
wartość odchylenia standardowego: 5999.081524350413


In [32]:

print(np.sin(wynik))

[[ 0.97848768 -0.79043321 -0.06192034]
 [-0.95906951  0.91360831  0.65028784]
 [ 0.14112001 -0.95892427  0.40351367]]


In [34]:
import math
print(math.sin(wynik))

TypeError: TypeError: only size-1 arrays can be converted to Python scalars