In [1]:
import tensorflow as tf
import numpy as np

In [2]:
print(tf.__version__)

2.10.1


In [3]:
mnist = tf.keras.datasets.mnist
(x_train,y_train),(x_test,y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0

11490434/11490434 [==============================] - 1s 0us/step


In [4]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.21909389, 0.42908213, 0.9563594 , 0.05106623, 0.04883438,
 -0.7055048 , -0.23664969, -0.48892322, 0.10607903, -0.3588401 ]],
 dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.07471678, 0.14286225, 0.24205333, 0.09789201, 0.09767377,
 0.04593806, 0.07341652, 0.057047 , 0.10342821, 0.06497214]],
 dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1],predictions).numpy()

3.0804615

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [10]:
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2950 - accuracy: 0.9137
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1420 - accuracy: 0.9582
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1064 - accuracy: 0.9680
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0870 - accuracy: 0.9730
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0754 - accuracy: 0.9761


In [11]:
model.evaluate(x_test,y_test,verbose=2)

313/313 - 1s - loss: 0.0709 - accuracy: 0.9781 - 597ms/epoch - 2ms/step


[0.07094055414199829, 0.9781000018119812]

In [12]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[6.2779418e-07, 1.9370217e-08, 7.4508966e-07, 1.1279838e-04,
        6.6610558e-12, 2.0207534e-07, 7.0296248e-13, 9.9988365e-01,
        1.3872386e-06, 5.6119626e-07],
       [5.4176628e-09, 1.4354080e-05, 9.9998331e-01, 2.3428236e-06,
        9.3275513e-17, 4.5932302e-09, 1.2896574e-10, 1.0996031e-13,
        3.1794858e-08, 1.2201033e-14],
       [1.4724812e-06, 9.9940646e-01, 3.3233533e-05, 2.3801963e-06,
        1.9343010e-05, 3.6272447e-06, 1.7037228e-05, 2.7849432e-04,
        2.3772815e-04, 2.4276471e-07],
       [9.9979860e-01, 5.8405909e-08, 2.4368848e-05, 9.2212355e-07,
        3.3124298e-08, 3.6400728e-05, 1.2303368e-05, 1.0568853e-04,
        1.2902946e-07, 2.1572891e-05],
       [2.2123526e-05, 1.9051374e-08, 1.7232120e-05, 3.4721282e-07,
        9.9640560e-01, 6.9631261e-07, 1.8343749e-06, 7.3972391e-05,
        5.8597390e-05, 3.4195844e-03]], dtype=float32)>